wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.7.13
    cli_version: 0.17.7
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1751353212
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      - 103
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 77
      - 103
      3:
      - 7
      - 13
      - 14
      - 23
      - 66
      4: 3.7.13
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: trainer/global_step
      6:
      - 3
